### ISSUE TITLE
Not able to send the message after successful connection to Jboss ActiveMQ via ampq

### ISSUE THREAD

**Issue by hverma11** [noodlefrenzy/node-amqp-1-0#43] opened 2015-02-09 03:12 UTC
HI,
 I have JBoss AMQ running locally with following connector configuration : 
     transportConnector name="amqp" uri="amqp://0.0.0.0:5672

I am trying to send a message using node-amqp-1-0 :+1 in nodeJs: 
var client = new AMQPClient(); // Uses PolicyBase default policy
client.connect('amqp://admin:admin@localhost/sqrQueue', function(conn_err) {
  // ... check for errors ...
  client.send(JSON.stringify({ key: "Value" }), function (send_err) {
    // ... check for errors ...
  });
  client.receive(function (rx_err, payload, annotations) {
    // ... check for errors ...
    console.log('Rx message: ');
    console.log(JSON.parse(payload));
  });
});

After doing this , i can see the producer in the JBOSS AMQ console but no messages. 

Please  correct me in case I missed anything or need more information,

**Comment by noodlefrenzy** [comment] 2015-02-09 03:38
Hey there, sorry, I haven't tried it with JBoss AMQ yet, I'll try and run it tomorrow and see if I can diagnose the issue.

In the meantime, you could try setting the environment variable ```DEBUG=amqp10*``` and see if the output has any obvious errors (but prepare for a lot of data).

**Comment by noodlefrenzy** [comment] 2015-02-09 21:56
Hey! I just tested this out with JBoss AMQ after setting it up to talk AMQP via https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_A-MQ/6.1/html/Client_Connectivity_Guide/AMQP.html#AMQP-Start

I saw some strange behavior, where JBoss was only sending a _single_ link credit at a time, and my internal canSend method had an off-by-one error that I'd never seen before because no other server I'd tested does that.

Anyway, I fixed that error and pushed a new release (0.0.11), and verified that I could send/receive to AMQ.  Please try it again and let me know if you're still seeing an issue.

One other thing I've noticed is that in the monitoring portal, I'm seeing the queue size remain the same even after I've received the message.  I've verified that if I reconnect, I don't re-receive already received messages, so it seems to be an internal book-keeping issue.  I have the receive link in "auto-settle" mode so that it shouldn't need to send back Disposition frames, but JBoss AMQ might be having a problem when it doesn't get those.  Like I said, operationally it doesn't seem to be causing a problem, but if it's holding on to internal resources it could be a problem.  I'll work on getting dispo frames working and see if that helps, but it could be a while.

Closing, but feel free to reopen if the problem isn't fixed on your end.

**Closed by noodlefrenzy** 2015-02-09 21:56 UTC
Labels: bug

**Comment by hverma11** [comment] 2015-02-09 22:37
Perfect ! Thanks for fixing and it is working fine now.

Cheers!

**Comment by noodlefrenzy** [comment] 2015-02-09 22:40
Great!  Glad to hear it!  Let me know if you run into other issues, especially with the disposition problem I mentioned above - I'm a bit worried about that behavior (since it's off-spec on their part).
